"""Add patch models for Milestone 7

Revision ID: 05ac6a021dbf
Revises: 52ec9870e49a
Create Date: 2026-07-06 12:35:58.664542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ac6a021dbf'
down_revision: Union[str, None] = '52ec9870e49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
