"""Add testing and QA models for Milestone 9

Revision ID: 1b3bf43a6154
Revises: 989afb973ac6
Create Date: 2026-07-06 13:10:38.681567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b3bf43a6154'
down_revision: Union[str, None] = '989afb973ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_job_id', sa.UUID(), nullable=False),
    sa.Column('line_coverage', sa.Float(), nullable=True),
    sa.Column('branch_coverage', sa.Float(), nullable=True),
    sa.Column('function_coverage', sa.Float(), nullable=True),
    sa.Column('statement_coverage', sa.Float(), nullable=True),
    sa.Column('covered_lines', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_job_id')
    )
    op.create_table('quality_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_job_id', sa.UUID(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('skipped_tests', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_job_id')
    )
    op.create_table('test_suites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_job_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED', 'ERROR', name='teststatus'), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('execution_job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED', 'ERROR', name='teststatus'), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('SYNTAX', 'ASSERTION', 'DEPENDENCY', 'RUNTIME', 'BUILD', 'ENVIRONMENT', 'FLAKY', 'UNKNOWN', name='failurecategory'), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('is_flaky', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_analyses')
    op.drop_table('test_executions')
    op.drop_table('test_cases')
    op.drop_table('test_suites')
    op.drop_table('quality_reports')
    op.drop_table('coverage_reports')
    # ### end Alembic commands ###
