"""Add patch models for Milestone 7

Revision ID: 52ec9870e49a
Revises: 32673468004d
Create Date: 2026-07-06 12:24:11.133840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52ec9870e49a'
down_revision: Union[str, None] = '32673468004d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_graphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('dependency_name', sa.String(length=255), nullable=False),
    sa.Column('version_constraint', sa.String(length=100), nullable=True),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('is_dev', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_graphs_dependency_name'), 'dependency_graphs', ['dependency_name'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_name'), 'knowledge_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_node_type'), 'knowledge_nodes', ['node_type'], unique=False)
    op.create_table('repository_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_indexes_file_path'), 'repository_indexes', ['file_path'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_relationship_type'), 'knowledge_edges', ['relationship_type'], unique=False)
    op.create_table('repository_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('frameworks', sa.JSON(), nullable=False),
    sa.Column('package_managers', sa.JSON(), nullable=False),
    sa.Column('architecture_patterns', sa.JSON(), nullable=False),
    sa.Column('architecture_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_patches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('unified_diff', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patch_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('diff_hunk', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['code_patches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patch_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patch_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['code_patches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patch_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['code_patches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_executions')
    op.drop_table('patch_reviews')
    op.drop_table('file_changes')
    op.drop_table('code_patches')
    op.drop_table('repository_analyses')
    op.drop_index(op.f('ix_knowledge_edges_relationship_type'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_table('repository_snapshots')
    op.drop_index(op.f('ix_repository_indexes_file_path'), table_name='repository_indexes')
    op.drop_table('repository_indexes')
    op.drop_index(op.f('ix_knowledge_nodes_node_type'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_name'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_dependency_graphs_dependency_name'), table_name='dependency_graphs')
    op.drop_table('dependency_graphs')
    # ### end Alembic commands ###
