"""Add testing and QA models for Milestone 9

Revision ID: a9b34c10b221
Revises: 1b3bf43a6154
Create Date: 2026-07-06 13:16:05.393772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b34c10b221'
down_revision: Union[str, None] = '1b3bf43a6154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
